name: my-frontend

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: dockdoinkorea/community-frontend:latest
    container_name: my-frontend
    ports:
      - "3000:3000"
    restart: always
    environment:
      API_TARGET: http://community.marcuth.store